### ISSUE TITLE
Timeout on DataServiceContext from Microsoft.OData.Client, Version=6.16.0.0, not honored

### ISSUE THREAD

**Issue by montyjain20** [OData/odata.net#1496]
After setting Timeout property on DataServiceContext , doesn't get honored when calling Odata WEbapi services and connection is maintained instead of closing after the time elapsed defined in Timeout property

### Assemblies affected

Microsoft.OData.Client Version=6.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

### Reproduce steps

Container container = new Container(new Uri(https://somewebapi)); container.Timeout = 1;
await container.SaveChangesAsync(SaveChangesOptions.PostOnlySetProperties);

### Expected result
Client connection closes out if call like SaveChangesAsync takes more than 1 second

*What would happen if there wasn't a bug.*

### Actual result
Client connection doesn't terminate till call is returned from the service so no client timeout

*What is actually happening.*

### Additional detail
Making Async call - so does it not use Timeout property or any additional things need to be set?

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@montyjain20 Do you see the same behavior in OData client 7.x version?

**Comment by montyjain20** [comment]
I haven't tried 7.x version as currently we are bound to use 6.16.0.0, Dou think its version issue and 7.x is fixed?

**Comment by xuzhg** [comment]
@montyjain20 thanks for your reply. So far, 6.x is in maintenance status, if 7.x also has the similar problem, it's better to fix on 7.x.

**Comment by montyjain20** [comment]
thanks @xuzhg . QQ is timeout property supported for ASync calls or only for sync calls. if not supported then each user of odata client library needs to implement own timeout if using async apis?

**Comment by AllTaken** [comment]
I believe I am still seeing this issue, although in my case it is not an async call.

**Comment by KenitoInc** [comment]
Closing this issue due to inactivity. If this issue still persists, feel free to create a new issue.
