### ISSUE TITLE
DataServiceContext cannot set custom HttpClient

### ISSUE THREAD

**Issue by midub** [OData/odata.net#2825]
During evaluation of new .NET Aspire I explored following inconvenience: DataServiceContext does not support custom HttpClient (from Dependency Injection with Service Discovery configured). I had to use this tutorial to get it working https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/client/using-httpclient.md

It is not a big issue, but I would prefer out of box solution next time. I would be grateful if you can solve this.

### Assemblies affected

Microsoft.OData.Client

### Reproduce steps

- Create DataServiceContext implementation with HttpClient injected using DI. 
- Register DataServiceContext  implementation in DI container. 
- Implement this approach https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/client/using-httpclient.md

### Expected result

Pass HttpClient directly to DataServiceContext base class. No need to search for and copy-paste code from tutorial.

### Additional detail

This is more likely change request. But would be nice to have.

**Comment by habbes** [comment]
Hello @midub, is this issue related to this: https://github.com/OData/odata.net/issues/2485

We added support for custom `HttpClientHandler` in this PR a while ago: https://github.com/OData/odata.net/pull/2431
which partially address the issue. The PR has some sample code on how to use this. But this could be a gap in the docs.

The reason we made provision for custom `HttpClientHandler` and not `HttpClient` was because we'd need to make breaking changes to safely support custom `HttpClient` instances, so that's something we've scheduled for the next major release.

**Comment by Mek7** [comment]
I ran into this issue today.
I have many unit tests and these tests make requests to local IIS using the odata client. When I run the tests, a few of them are successful, but then every test fails after 2 minutes. The problem is that local IIS stops handling requests at all (instead of returning a meaningful HTTP error) and lets them time out, because my Windows is not a Server edition (there is a limitation of IIS requests in non-server windows editions due to licensing). Any local website served by IIS is also not available - keeps loading and loading forever. When I issue "iisreset" command in command line, I get:

```
Attempting stop...
Restart attempt failed.
Access denied, you must be an administrator of the remote computer to use this
command. Either have your account added to the administrator local group of
the remote computer or to the domain administrator global group.
```
Yes, I am an administrator. When I do the same iisreset second time, it succeeds and brings IIS back to life.
I am now refactoring code to use the odata client (and generated proxy classes) instead of manual http requests via HttpClient. In previous version of the code, where there was only one HttpClient instance that was static and heavily re-used, I didn't get this problem.
How can I influence odata client to do the same - reuse connections, reuse the same HttpClient, to not kill local IIS?
Note: the code is not .NET core, but .NET Framework 4.8.

**Comment by habbes** [comment]
@Mek7 you could try to pass a `HttpClientHandlerProvider` and make it reuse the same `HttpClientHandler` for all requests.

```c#
// usage
var handlerProvider = new HttpClientHandlerProvider();
var dataServiceContext = new DataServiceContext(new Uri("https://service.org/odata"), handlerProvider);
dataServiceContext.HttpRequestTransportMode = HttpRequestTransportMode.HttpClient;
dataServiceContext.HttpClientHandlerProvider = handlerProvider;

var peopleQuery = dataServiceContext.CreateQuery<Person>();
var people = await peopleQuery.ExecuteAsync();

// handler provider definition

class HttpClientHandlerProvider : IHttpClientHandlerProvider
{
    private HttpClientHandler _handler;

    public HttpClientHandlerProvider()
    {
        _handler = new HttpClientHandler();
        // handler configurations
        handler.Credentials = ...;
        handler.ServerCertificateCustomValidationCallback = ...;
    }

    public HttpClientHandler GetHttpClientHandler()
    {
        return _handler;
    }
}
```

**Comment by Mek7** [comment]
@habbes Forgot to mention that I already implemented the `HttpClientHandlerProvider ` the same way as you suggested. I thought that it will solve this problem, but it did not.

**Comment by habbes** [comment]
@Mek7 could you share some code snippets showing how you're `DataServiceContext` is configured and set up?

**Comment by Mek7** [comment]
Sure, here is my code.
There is a static class named `SystemApiProvider` that has static container (generated from odata service metadata). `SystemApiProvider` contains static methods to access the odata service using the static container.
Some non-interesting parts are left out.
`AsyncRetryPolicy` is a class from Polly nuget package.
```
    public class SystemApiProvider : ISystemApiProvider
    {
        private readonly SystemApiContainer container;
        private string accessToken;
        private readonly AsyncRetryPolicy retryPolicy;
        private ILogger Logger { get; set; }

        public SystemApiProvider()
        {
            this.Logger = LogFactory.CreateLogger();
            this.container = new SystemApiContainer(new Uri(ConfigurationSettings.SystemApiUri + ConfigurationSettings.SystemApiUriODataSegment))
            {
                // configure custom HttpClientHandlerProvider that will be re-used between requests to improve performance
                HttpClientHandlerProvider = new SystemApiHttpClientHandlerProvider()
            };

            this.container.SendingRequest2 += (object sender, SendingRequest2EventArgs e) =>
            {
                e.RequestMessage.SetHeader(HttpRequestHeader.Authorization.ToString(), CommonConstants.AuthenticationHeaderValueBearer + " " + this.accessToken);
            };

            this.retryPolicy = Policy
                .Handle<DataServiceQueryException>()
                .WaitAndRetryAsync(
                    3,
                    retryAttempt => TimeSpan.FromMilliseconds(500 * retryAttempt),
                    (exception, timeSpan, retryCount, context) =>
                    {
                        if (exception is DataServiceQueryException dsqe
                            && (dsqe.Response.StatusCode == (int)HttpStatusCode.InternalServerError))
                        {
                            var message = string.Format(
                                CultureInfo.InvariantCulture,
                                "Retry request to SystemApi, retry count {0}, ended with response {1}. Address: {2}",
                                retryCount,
                                dsqe.Response.StatusCode,
                                dsqe.Response.Query?.RequestUri);

                            if (retryCount == 3)
                            {
                                this.Logger.Error(message, exception);
                            }
                            else
                            {
                                this.Logger.WarnException(message, exception);
                            }
                        }
                    });
        }

        public async Task<OAuthApplication> GetOAuthApplicationByName(string name)
        {
            return (await this.CallSystemApiQuery(
                async () => await this.container.OAuthApplication
                    .Where(oa => oa.Name == name)
                    .ExecuteODataQueryAsync()))
                .FirstOrDefault();
        }

        private async Task<TResult> CallSystemApiQuery<TResult>(Func<Task<TResult>> containerAction, bool returnDefaultOnNotFound = false)
        {
            return await this.retryPolicy.ExecuteAsync(async () =>
            {
                TResult resultEntity;

                try
                {
                    resultEntity = await containerAction();
                }
                catch (DataServiceQueryException dsqe) when (dsqe.Response.StatusCode == (int)HttpStatusCode.Unauthorized)
                {
                    // access token is invalid, get a new one and try again
                    // NOTE: other status codes are handled by retryPolicy
                    // // // ... some other code...
                    resultEntity = await containerAction();
                }
                catch (DataServiceQueryException dsqe) when (dsqe.Response.StatusCode == (int)HttpStatusCode.NotFound && returnDefaultOnNotFound)
                {
                    resultEntity = default;
                }

                return resultEntity;
            });
        }
    }
```
This is the `ExecuteODataQueryAsync` extension method (as per #2839 )
```
    public static class QueryableExtensions
    {
        /// <summary>
        /// Executes OData query that has been composed via LINQ
        /// https://github.com/OData/odata.net/issues/2839
        /// </summary>
        /// <typeparam name="TSource">Type of current IQueryable instance</typeparam>
        /// <param name="originalQuery"></param>
        /// <returns></returns>
        public static async Task<IEnumerable<TSource>> ExecuteODataQueryAsync<TSource>(this IQueryable<TSource> originalQuery)
        {
            var query = new DataServiceQuery<TSource>(originalQuery.Expression, originalQuery.Provider as DataServiceQueryProvider);
            return await query.ExecuteAsync();
        }
    }
```
The `GetOAuthApplicationByName` method above is an example query, there are many like that. Some load a collection of entities, some load a single by ID, there are some filtered queries using .Where(), and some custom odata actions and function.
Can you see something particularly wrong here?

**Comment by habbes** [comment]
@midub thanks. From the snippet above, `SystemApiContainer` is the generated `DataServiceContext`, right?

You should set the transport mode to `HttpClient`. The default is `HttpWebRequest` (we'll change the default in the next major release):

```diff
 this.container = new SystemApiContainer(new Uri(ConfigurationSettings.SystemApiUri + ConfigurationSettings.SystemApiUriODataSegment))
            {
+              HttpRequestTransportMode = HttpRequestTransportMode.HttpClient
                // configure custom HttpClientHandlerProvider that will be re-used between requests to improve performance
                HttpClientHandlerProvider = new SystemApiHttpClientHandlerProvider()
            };
```

In case this does not solve your problem, it would be great to also see the definition of your `SystemApiHttpClientHandlerProvider` class.

**Comment by Mek7** [comment]
@habbes Yeah, that was the culprit. For some reason I was under impression that `HttpClient` is the default, I read that in a comment somewhere but can't remember where. And maybe there was `WebClient` written in that comment but I misread that.
Anyway, it works now. You are a life savior, thanks :)

**Comment by habbes** [comment]
Closing this issue now. @midub if your problem has not be solved, feel free to re-open the issue.
